In [36]:
from path import Path
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import seaborn as sns

In [37]:
data = Path('../raw_data/LogregStandard.csv')
df = pd.read_csv(data)
df.head()

income 10  Under 10k with   Under 10k without  10 to 20 income  % with  \
0       5000                0               0.30            15000       0   
1       5000                0               0.33            15000       0   
2       5000                0               0.51            15000       0   
3       5000                0               0.31            15000       0   
4       5000                0               0.39            15000       0   

   10 to 20 without  20 to 35 income  20 to 35 with  20 to 35 without  \
0              0.30            27500              1              0.19   
1              0.43            27500              0              0.31   
2              0.22            27500              0              0.29   
3              0.51            27500              0              0.33   
4              0.45            27500              0              0.33   

   35 to 50 income  35 to 50 with  35 to 50 without  50 to 75 income  \
0            42500              0              0.16            62500   
1            42500              0              0.30            62500   
2            42500              0              0.16            62500   
3            42500              1              0.10            62500   
4            42500              1              0.12            62500   

   50 to 75 With  50 to 75 Without  over 75 income  75+ with  75+ without  
0              0              0.24           80000         1         0.05  
1              1              0.05           80000         1         0.12  
2              1              0.13           80000         1         0.10  
3              1              0.07           80000         1         0.05  
4              1              0.11           80000         1         0.08

In [3]:
df.dropna()

income 10  Under 10k with   Under 10k without  10 to 20 income  % with  \
0       5000.0              0.0               0.30          15000.0     0.0   
1       5000.0              0.0               0.33          15000.0     0.0   
2       5000.0              0.0               0.51          15000.0     0.0   
3       5000.0              0.0               0.31          15000.0     0.0   
4       5000.0              0.0               0.39          15000.0     0.0   
..         ...              ...                ...              ...     ...   
831     5000.0              0.0               0.45          15000.0     0.0   
832     5000.0              0.0               0.72          15000.0     0.0   
833     5000.0              0.0               0.77          15000.0     0.0   
834     5000.0              0.0               0.76          15000.0     0.0   
835     5000.0              0.0               0.47          15000.0     0.0   

     10 to 20 without  20 to 35 income  20 to 35 with  20 to 35 without  \
0                0.30          27500.0            1.0              0.19   
1                0.43          27500.0            0.0              0.31   
2                0.22          27500.0            0.0              0.29   
3                0.51          27500.0            0.0              0.33   
4                0.45          27500.0            0.0              0.33   
..                ...              ...            ...               ...   
831              0.36          27500.0            0.0              0.27   
832              0.61          27500.0            0.0              0.46   
833              0.79          27500.0            0.0              0.82   
834              0.70          27500.0            0.0              0.57   
835              0.35          27500.0            0.0              0.26   

     35 to 50 income  35 to 50 with  35 to 50 without  50 to 75 income  \
0            42500.0            0.0              0.16          62500.0   
1            42500.0            0.0              0.30          62500.0   
2            42500.0            0.0              0.16          62500.0   
3            42500.0            1.0              0.10          62500.0   
4            42500.0            1.0              0.12          62500.0   
..               ...            ...               ...              ...   
831          42500.0            0.0              0.23          62500.0   
832          42500.0            0.0              0.30          62500.0   
833          42500.0            0.0              0.52          62500.0   
834          42500.0            0.0              0.46          62500.0   
835          42500.0            1.0              0.10          62500.0   

     50 to 75 With  50 to 75 Without  over 75 income  75+ with  75+ without  
0              0.0              0.24         80000.0       1.0         0.05  
1              1.0              0.05         80000.0       1.0         0.12  
2              1.0              0.13         80000.0       1.0         0.10  
3              1.0              0.07         80000.0       1.0         0.05  
4              1.0              0.11         80000.0       1.0         0.08  
..             ...               ...             ...       ...          ...  
831            1.0              0.09         80000.0       1.0         0.09  
832            0.0              0.32         80000.0       1.0         0.07  
833            0.0              0.62         80000.0       0.0         0.24  
834            0.0              0.56         80000.0       0.0         0.22  
835            1.0              0.07         80000.0       1.0         0.02  

[836 rows x 18 columns]

## Under 10k LogReg

In [4]:
# Name the variable
y = df["Under 10k with "]
X = df.drop(columns="Under 10k with ")

In [5]:
# Split into test/train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=100,
   random_state=1)

In [7]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [8]:
y_pred = classifier.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9665071770334929


In [10]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[202   0]
 [  7   0]]


In [11]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98       202
         1.0       0.00      0.00      0.00         7

    accuracy                           0.97       209
   macro avg       0.48      0.50      0.49       209
weighted avg       0.93      0.97      0.95       209



C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# # 10 to 20k Log Reg

In [12]:
y = df["% with"]
X = df.drop(columns="% with")

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

In [14]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [15]:
y_pred = classifier.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9665071770334929


In [17]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[202   0]
 [  7   0]]


In [18]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98       202
         1.0       0.00      0.00      0.00         7

    accuracy                           0.97       209
   macro avg       0.48      0.50      0.49       209
weighted avg       0.93      0.97      0.95       209



C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# # 20 to 35k LR

In [19]:
y = df["20 to 35 with"]
X = df.drop(columns="20 to 35 with")

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

In [21]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [22]:
y_pred = classifier.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8995215311004785


In [24]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[188   0]
 [ 21   0]]


In [25]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

         0.0       0.90      1.00      0.95       188
         1.0       0.00      0.00      0.00        21

    accuracy                           0.90       209
   macro avg       0.45      0.50      0.47       209
weighted avg       0.81      0.90      0.85       209



C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# # 35 to 50k LR

In [26]:
y = df["35 to 50 with"]
X = df.drop(columns="35 to 50 with")

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

In [28]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.49282296650717705


In [31]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[  0 106]
 [  0 103]]


In [32]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       106
         1.0       0.49      1.00      0.66       103

    accuracy                           0.49       209
   macro avg       0.25      0.50      0.33       209
weighted avg       0.24      0.49      0.33       209



C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
y = df["50 to 75 With"]
X = df.drop(columns="50 to 75 With")

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

In [40]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8851674641148325


In [43]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[  0  24]
 [  0 185]]


In [44]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        24
           1       0.89      1.00      0.94       185

    accuracy                           0.89       209
   macro avg       0.44      0.50      0.47       209
weighted avg       0.78      0.89      0.83       209



C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
y = df["75+ with"]
X = df.drop(columns="75+ with")

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

In [47]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [48]:
y_pred = classifier.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9952153110047847


In [50]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[  0   1]
 [  0 208]]


In [51]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      1.00      1.00       208

    accuracy                           1.00       209
   macro avg       0.50      0.50      0.50       209
weighted avg       0.99      1.00      0.99       209



C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\owner\anaconda3\envs\PythonData\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
